# Generated by Django 4.0.1 on 2022-01-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercountry',
            options={'ordering': ['-year'], 'verbose_name': 'User country', 'verbose_name_plural': 'User countries'},
        ),
        migrations.AddField(
            model_name='usercountry',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usercountry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
    ]
