# Generated by Django 4.0.1 on 2022-01-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_usercountry_options_usercountry_foto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercountry',
            options={'ordering': ['year'], 'verbose_name': 'User country', 'verbose_name_plural': 'User countries'},
        ),
    ]
