# Generated by Django 3.2.11 on 2024-02-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20240224_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregion',
            name='country',
        ),
        migrations.AddField(
            model_name='userregion',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='countries.region'),
            preserve_default=False,
        ),
    ]
